# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2345842f8224b3061d8a06d29953edfa28cf5dad041d7e4d414244008719a630d703b09dac13edb2daf61ac7a76991b8c2b91581540b051e30330bc77980f26

test:
  secret_key_base: a1fcd027a1a01405c765899954e00e683fd85b8f504c6a728fbfdd4fbcbf5314200679adeffed4e73087bf4d74de2011069f736a7210b3e476e3b4c8b4e9dd25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
